# Generated by Django 6.1 on 2026-08-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment', models.TextField()),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField()),
                ('consultation_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
