# Generated by Django 6.1 on 2026-08-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedLab',
            fields=[
                ('lab_prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_id', models.IntegerField()),
                ('test_id', models.IntegerField()),
                ('test_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
    ]
