# Generated by Django 6.1 on 2026-09-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_id', models.IntegerField()),
                ('medicine_id', models.CharField(max_length=20)),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=100)),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
                ('food_timing', models.CharField(blank=True, choices=[('Before Food', 'Before Food'), ('After Food', 'After Food')], max_length=20, null=True)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medical_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
