# Generated by Django 6.1 on 2026-09-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_prescribedmedicine_consultation_doctor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedlab',
            name='consultation_id',
        ),
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='consultation_id',
        ),
        migrations.AddField(
            model_name='prescribedlab',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tests', to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicines', to='doctor.consultation'),
        ),
    ]
