# Generated by Django 6.1 on 2026-09-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_prescribedlab_consultation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedlab',
            name='test_id',
            field=models.CharField(max_length=20),
        ),
    ]
