# Generated by Django 6.1 on 2026-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_prescribedlab_results_prescribedlab_technician_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedicine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
