# Generated by Django 6.1 on 2026-09-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
