# Generated by Django 6.1 on 2026-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_prescribedmedicine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
