# Generated by Django 6.1 on 2026-09-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('lab_bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_prescription_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=150)),
                ('doctor_id', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('test_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='paid', max_length=20)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], max_length=30)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
