# Generated by Django 6.1 on 2026-09-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_labbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedicine',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
