# Generated by Django 6.1 on 2026-09-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('test_name', models.CharField(max_length=150)),
                ('normal_range', models.CharField(max_length=100)),
                ('sample_required', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('tat', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
