# Generated by Django 6.1 on 2026-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
