# Generated by Django 6.1 on 2026-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_staff_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
