# Generated by Django 6.1 on 2026-08-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Active', max_length=20)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
