# Generated by Django 6.1 on 2026-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token_no',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
