# Generated by Django 6.1 on 2026-09-04 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0003_alter_appointment_token_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=150)),
                ('doctor_id', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='paid', max_length=20)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], max_length=30)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_bills', to='receptionist.appointment')),
            ],
        ),
    ]
